Extend -fno-plt to normal non-PIC branches on x86
This patch extends -fno-plt to normal non-PIC branches on x86.  -fno-plt
works in 64-bit mode with the existing binutils.  For 32-bit, we need
the updated assembler and linker to support "call/jmp *foo@GOT" with
a new relocation different from R_386_GOT32 to indicate that this
relocation applies to indirect branches.  A configure time check is
added to verify that 32-bit assembler generates a known relocation
which is different from R_386_GOT32.  A new 32-bit relocaton is needed
since "call/jmp *foo@GOT" requires a different relocation from R_386_GOT32
which is used together with a GOT register in "call/jmp *foo@GOT(%reg)".

gcc/

	* configure.ac (HAVE_AS_INDIRECT_BRANCH_VIA_GOT): New.  Defined
	to 1 if 32-bit assembler generates a known relocation which is
	different from R_386_GOT32.
	* config.in: Regenerated.
	* configure: Likewise.
	* config/i386/i386.c (ix86_output_call_insn):  Extend -fno-plt
	to normal non-PIC branches.
	* config/i386/i386.h (TARGET_ELF): New.

gcc/testsuite/

	* gcc.target/i386/pr66232-6.c: New tests.
	* gcc.target/i386/pr66232-7.c: Likewise.
	* gcc.target/i386/pr66232-8.c: Likewise.
	* gcc.target/i386/pr66232-9.c: Likewise.
	* gcc.target/i386/pr66232-10.c: Likewise.
	* gcc.target/i386/pr66232-11.c: Likewise.
	* gcc.target/i386/pr66232-12.c: Likewise.
	* gcc.target/i386/pr66232-13.c: Likewise.
	* lib/target-supports.exp (check_effective_target_branch_via_got):
	New.

HAVE_AS_INDIRECT_BRANCH_VIA_GOT

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -25361,7 +25361,7 @@ $as_echo "#define HAVE_AS_IX86_DIFF_SECT_DELTA 1" >>confdefs.h
 
 fi
 
-    # These two are used unconditionally by i386.[ch]; it is to be defined
+    # These three are used unconditionally by i386.[ch]; it is to be defined
     # to 1 if the feature is present, 0 otherwise.
     as_ix86_gotoff_in_data_opt=
     if test x$gas = xyes; then
@@ -25404,6 +25404,50 @@ $as_echo "$gcc_cv_as_ix86_gotoff_in_data" >&6; }
 
 cat >>confdefs.h <<_ACEOF
 #define HAVE_AS_GOTOFF_IN_DATA `if test $gcc_cv_as_ix86_gotoff_in_data = yes; then echo 1; else echo 0; fi`
+_ACEOF
+
+
+    as_ix86_indirect_branch_via_got_opt=
+    if test x$gas = xyes; then
+      as_ix86_indirect_branch_via_got_opt="--32"
+    fi
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking assembler for call *foo@GOT" >&5
+$as_echo_n "checking assembler for call *foo@GOT... " >&6; }
+if test "${gcc_cv_as_ix86_indirect_branch_via_got+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+  gcc_cv_as_ix86_indirect_branch_via_got=no
+    if test $in_tree_gas = yes; then
+    if test $gcc_cv_gas_vers -ge `expr \( \( 2 \* 1000 \) + 26 \) \* 1000 + 0`
+  then gcc_cv_as_ix86_indirect_branch_via_got=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    $as_echo '	.text
+	call *foo@GOT' > conftest.s
+    if { ac_try='$gcc_cv_as $gcc_cv_as_flags $as_ix86_indirect_branch_via_got_opt -o conftest.o conftest.s >&5'
+  { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_try\""; } >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; }
+    then
+	if test x$gcc_cv_readelf != x \
+	 && $gcc_cv_readelf -r conftest.o | grep R_386_ | grep -v R_386_GOT32 > /dev/null 2>&1; then
+	   gcc_cv_as_ix86_indirect_branch_via_got=yes
+	 fi
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $gcc_cv_as_ix86_indirect_branch_via_got" >&5
+$as_echo "$gcc_cv_as_ix86_indirect_branch_via_got" >&6; }
+
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_AS_INDIRECT_BRANCH_VIA_GOT `if test x"$gcc_cv_as_ix86_indirect_branch_via_got" = xyes; then echo 1; else echo 0; fi`
 _ACEOF
 
 
